<?php 
return [
'admin_name' => 'Fernando',
'title_site' => 'Ecomsail',
'url_site' => 'https://ecomsail.bahiaxip.com',
'email_site' => 'manu@gmail.com',
'phone_site' => '627 64 66 25',
'whatsapp' => '627646625',
'facebook' => 'http://www.google.es',
'twitter' => '',
'instagram' => '',
'linkedin' => 'https://www.linkedin.com/feed/',
'coin' => '€',
'position_coin' => '0',
'button_adding_product' => 'on',
'items_per_page' => '10',
'payment_paypal' => 'on',
'send_email' => 'on',
'send_not' => 'on',
'standard_tax' => '21',
'reduce_tax' => '4',
'zero_tax' => '0',
'main_slider' => 'on',
'time_interval' => '5',
]
?>
