<?php
//necesario cambiar el namespace por la ruta correspondiente
namespace App\Functions;
class Prov {
public $prov = [ 
0 => ['provincia_id' => '02','nombre' => 'Albacete'],
1 => ['provincia_id' => '03','nombre' => 'Alicante/Alacant'],
2 => ['provincia_id' => '04','nombre' => 'Almería'],
3 => ['provincia_id' => '01','nombre' => 'Araba/Álava'],
4 => ['provincia_id' => '33','nombre' => 'Asturias'],
5 => ['provincia_id' => '05','nombre' => 'Ávila'],
6 => ['provincia_id' => '06','nombre' => 'Badajoz'],
7 => ['provincia_id' => '07','nombre' => 'Balears, Illes'],
8 => ['provincia_id' => '08','nombre' => 'Barcelona'],
9 => ['provincia_id' => '48','nombre' => 'Bizkaia'],
10 => ['provincia_id' => '09','nombre' => 'Burgos'],
11 => ['provincia_id' => '10','nombre' => 'Cáceres'],
12 => ['provincia_id' => '11','nombre' => 'Cádiz'],
13 => ['provincia_id' => '39','nombre' => 'Cantabria'],
14 => ['provincia_id' => '12','nombre' => 'Castellón/Castelló'],
15 => ['provincia_id' => '13','nombre' => 'Ciudad Real'],
16 => ['provincia_id' => '14','nombre' => 'Córdoba'],
17 => ['provincia_id' => '15','nombre' => 'Coruña, A'],
18 => ['provincia_id' => '16','nombre' => 'Cuenca'],
19 => ['provincia_id' => '20','nombre' => 'Gipuzkoa'],
20 => ['provincia_id' => '17','nombre' => 'Girona'],
21 => ['provincia_id' => '18','nombre' => 'Granada'],
22 => ['provincia_id' => '19','nombre' => 'Guadalajara'],
23 => ['provincia_id' => '21','nombre' => 'Huelva'],
24 => ['provincia_id' => '22','nombre' => 'Huesca'],
25 => ['provincia_id' => '23','nombre' => 'Jaén'],
26 => ['provincia_id' => '24','nombre' => 'León'],
27 => ['provincia_id' => '25','nombre' => 'Lleida'],
28 => ['provincia_id' => '27','nombre' => 'Lugo'],
29 => ['provincia_id' => '28','nombre' => 'Madrid'],
30 => ['provincia_id' => '29','nombre' => 'Málaga'],
31 => ['provincia_id' => '30','nombre' => 'Murcia'],
32 => ['provincia_id' => '31','nombre' => 'Navarra'],
33 => ['provincia_id' => '32','nombre' => 'Ourense'],
34 => ['provincia_id' => '34','nombre' => 'Palencia'],
35 => ['provincia_id' => '35','nombre' => 'Palmas, Las'],
36 => ['provincia_id' => '36','nombre' => 'Pontevedra'],
37 => ['provincia_id' => '26','nombre' => 'Rioja, La'],
38 => ['provincia_id' => '37','nombre' => 'Salamanca'],
39 => ['provincia_id' => '38','nombre' => 'Santa Cruz de Tenerife'],
40 => ['provincia_id' => '40','nombre' => 'Segovia'],
41 => ['provincia_id' => '41','nombre' => 'Sevilla'],
42 => ['provincia_id' => '42','nombre' => 'Soria'],
43 => ['provincia_id' => '43','nombre' => 'Tarragona'],
44 => ['provincia_id' => '44','nombre' => 'Teruel'],
45 => ['provincia_id' => '45','nombre' => 'Toledo'],
46 => ['provincia_id' => '46','nombre' => 'Valencia/València'],
47 => ['provincia_id' => '47','nombre' => 'Valladolid'],
48 => ['provincia_id' => '49','nombre' => 'Zamora'],
49 => ['provincia_id' => '50','nombre' => 'Zaragoza'],
50 => ['provincia_id' => '51','nombre' => 'Ceuta'],
51 => ['provincia_id' => '52','nombre' => 'Melilla'],
];
}
?>
